name = "DeformableMirrors"
uuid = "1974dd6c-e1e0-4652-a3c9-2f0e18898c7e"
authors = ["Oleg Soloviev"]
version = "0.1.0"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
CairoMakieExt = "CairoMakie"
GLMakieExt = "GLMakie"
MakieExt = "Makie"

[compat]
GLMakie = "0.11.5"
GeometryBasics = "0.5.7"
Makie = "0.22.4"
julia = "1"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CairoMakie"]
